---
### 난수발생

In [12]:
import numpy as np


In [20]:
# Boolean Indexing

names = np.array(
  [
    "Charles",
    "Kenny",
    "Hayoung",
    "Charles",
    "Hayoung",
    "Kenny",
    "Kenny"
  ]
)

np.random.seed(4) # 난수 발생 고정 
data = np.random.randn(7, 4) # 가우시안 정규 분포
data

array([[ 0.05056171,  0.49995133, -0.99590893,  0.69359851],
       [-0.41830152, -1.58457724, -0.64770677,  0.59857517],
       [ 0.33225003, -1.14747663,  0.61866969, -0.08798693],
       [ 0.4250724 ,  0.33225315, -1.15681626,  0.35099715],
       [-0.60688728,  1.54697933,  0.72334161,  0.04613557],
       [-0.98299165,  0.05443274,  0.15989294, -1.20894816],
       [ 2.22336022,  0.39429521,  1.69235772, -1.11281215]])

In [21]:
# data의 크기 확인
data.shape

(7, 4)

In [22]:
names == 'Charles'

array([ True, False, False,  True, False, False, False])

In [23]:
data[names == 'Charles', :]

array([[ 0.05056171,  0.49995133, -0.99590893,  0.69359851],
       [ 0.4250724 ,  0.33225315, -1.15681626,  0.35099715]])

In [26]:
data[(names == "Charles") | (names == "Kenny"), :]

array([[ 0.05056171,  0.49995133, -0.99590893,  0.69359851],
       [-0.41830152, -1.58457724, -0.64770677,  0.59857517],
       [ 0.4250724 ,  0.33225315, -1.15681626,  0.35099715],
       [-0.98299165,  0.05443274,  0.15989294, -1.20894816],
       [ 2.22336022,  0.39429521,  1.69235772, -1.11281215]])

---
### reshape

In [27]:
# 1부터 8까지의 Array 생성
arr = np.arange(1, 9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
# 2차원 배열로 변경
arr1 = np.reshape(arr, (2,4)) # 행,열
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
# 3차원 배열로 변경
arr2 = np.reshape(arr,(2,2,2)) # Page, Row, Column
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
# 2차원 배열을 1차원 변경
arr3 = arr1.reshape(-1, 1)
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [33]:
arr3[0][0]

1