### Numpy

In [1]:
import numpy as np

In [2]:
# List로 만들기
data1 = [
  6,
  7.5,
  8,
  0,
  1
]

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
# 배열의 크기
arr1.shape

(5,)

In [4]:
data2 = [
  [1,2,3,4],
  [5,6,7,8]
]

arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
# 배열의 크기
arr2.shape

(2, 4)

In [6]:
# 0으로 구성된 1차원 array 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
# 1로 구성된 1차원 array  생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
# 특정숫자(10)으로 구성된 array 5개 생성
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [11]:
# 0으로 구성된 3행 5열 2차원 array 생성
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.full((3,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [16]:
a = np.zeros((1920, 1080))
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
a.shape

(1920, 1080)

In [20]:
# 범위가 있는 array 생성
list(range(15))
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

---
### 연산

In [21]:
arr1 = np.array(
  (
    [1,2,3],
    [4,5,6]
  ),
  dtype=np.float64
)
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
arr2 = np.array(
  (
    [7,8,9],
    [10,11,12]
  ),
  dtype=np.float64
)
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [23]:
# 덧셈
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [24]:
# arr1을 2배 키우기
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [28]:
# arr1의 제곱근 구하기

np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

---
### Data Handling

In [29]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# index가 5인 데이터 불러오기
arr[5]

5

In [32]:
# Slicing: Index 범위 
# 5,6,7,8
arr[5:9]

array([5, 6, 7, 8])

In [33]:
# arr의 처음부터 4번 index값 불러오기
arr[:5]

array([0, 1, 2, 3, 4])

---
### 2차원 배열

In [34]:
arr2d = np.array(
  [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16],
  ]
)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
# 2번 행의 자료 추출하기
arr2d[2,:]

array([ 9, 10, 11, 12])

In [36]:
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
arr2d[:,3]

array([ 4,  8, 12, 16])

In [39]:
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [42]:
arr2d[:2,1:3] = 0
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])